name: Create PDF from README

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://dalibo/pandocker:latest
        with: # needs a README in your repo root!
          args: "-o README.pdf --toc --pdf-engine=xelatex --template=eisvogel --listing"
      - uses: actions/upload-artifact@master
        with:
          name: readme.pdf
          path: output
      - uses: docker://pandoc/latex:2.9
        with: # needs a README in your repo root!
          args: "--standalone --output=output/README.docx README.md"
      - uses: actions/upload-artifact@master
        with:
          name: readme.docx
          path: output
